{{ if lookPath "tmux" }}
[".config/tmux/plugins/tpm"]
    type = "archive"
    url = "https://github.com/tmux-plugins/tpm/archive/refs/heads/master.tar.gz"
    exact = true
    stripComponents = 1
    refreshPeriod = "168h"
{{ end }}
{{ if lookPath "emacs" }}
[".config/minimal-emacs.d"]
    type = "git-repo"
    url = "https://github.com/jamescherti/minimal-emacs.d.git"
    refreshPeriod = "168h"
    [".config/minimal-emacs.d".clone]
        args = ["--depth -1"]
{{ end }}
